# Generated by Django 4.1.3 on 2022-12-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('PlaylistId', models.AutoField(primary_key=True, serialize=False)),
                ('PlaylistName', models.CharField(max_length=500)),
            ],
        ),
    ]
