# Generated by Django 4.1.3 on 2022-12-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyCloneApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlists',
            old_name='PlaylistId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='playlists',
            old_name='PlaylistName',
            new_name='name',
        ),
    ]
